export const GET_CHARACTERS_REQUEST = 'GET_CHARACTERS_REQUEST';
export const GET_CHARACTERS_SUCCESS = 'GET_CHARACTERS_SUCCESS';
export const GET_CHARACTERS_ERROR = 'GET_CHARACTERS_REQUEST';

export const GET_CHARACTERS_COLLECTIONS_REQUEST = 'GET_CHARACTERS_COLLECTIONS_REQUEST';
export const GET_CHARACTERS_COLLECTIONS_SUCCESS = 'GET_CHARACTERS_COLLECTIONS_SUCCESS';
export const GET_CHARACTERS_COLLECTIONS_ERROR = 'GET_CHARACTERS_COLLECTIONS_REQUEST';

export default {
  GET_CHARACTERS_REQUEST,
  GET_CHARACTERS_SUCCESS,
  GET_CHARACTERS_ERROR,
  GET_CHARACTERS_COLLECTIONS_REQUEST,
  GET_CHARACTERS_COLLECTIONS_SUCCESS,
  GET_CHARACTERS_COLLECTIONS_ERROR,
};
