export const GET_COMICS_REQUEST = 'GET_COMICS_REQUEST';
export const GET_COMICS_SUCCESS = 'GET_COMICS_SUCCESS';
export const GET_COMICS_ERROR = 'GET_COMICS_REQUEST';

export default {
  GET_COMICS_REQUEST,
  GET_COMICS_SUCCESS,
  GET_COMICS_ERROR
};
