export const GET_SERIES_REQUEST = 'GET_SERIES_REQUEST';
export const GET_SERIES_SUCCESS = 'GET_SERIES_SUCCESS';
export const GET_SERIES_ERROR = 'GET_SERIES_REQUEST';

export default {
  GET_SERIES_REQUEST,
  GET_SERIES_SUCCESS,
  GET_SERIES_ERROR
};
