export const GET_STORIES_REQUEST = 'GET_STORIES_REQUEST';
export const GET_STORIES_SUCCESS = 'GET_STORIES_SUCCESS';
export const GET_STORIES_ERROR = 'GET_STORIES_REQUEST';

export default {
  GET_STORIES_REQUEST,
  GET_STORIES_SUCCESS,
  GET_STORIES_ERROR
};
