export const REQUEST = 'REQUEST';
export const SUCCESS = 'SUCCESS';
export const ERROR = 'REQUEST';
export const COLLECTIONS_REQUEST = 'COLLECTIONS_REQUEST';
export const COLLECTIONS_SUCCESS = 'COLLECTIONS_SUCCESS';
export const COLLECTIONS_ERROR = 'COLLECTIONS_ERROR';

export default {
  REQUEST,
  SUCCESS,
  ERROR,
  COLLECTIONS_REQUEST,
  COLLECTIONS_SUCCESS,
  COLLECTIONS_ERROR
};
